/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MemberRouteImport } from './routes/member'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InchargeRouteImport } from './routes/incharge'
import { Route as CeoRouteImport } from './routes/ceo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberIndexRouteImport } from './routes/member.index'
import { Route as InchargeIndexRouteImport } from './routes/incharge.index'
import { Route as CeoIndexRouteImport } from './routes/ceo.index'
import { Route as MemberFocusRouteImport } from './routes/member.focus'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as InchargeReviewsRouteImport } from './routes/incharge.reviews'
import { Route as InchargeAttendanceRouteImport } from './routes/incharge.attendance'
import { Route as CeoSeedRouteImport } from './routes/ceo.seed'
import { Route as CeoFranchisesRouteImport } from './routes/ceo.franchises'
import { Route as CeoAttendanceRouteImport } from './routes/ceo.attendance'
import { Route as CeoAssignRouteImport } from './routes/ceo.assign'
import { Route as CeoCoursesIndexRouteImport } from './routes/ceo.courses.index'
import { Route as MemberCoursesIdRouteImport } from './routes/member.courses.$id'
import { Route as CeoCoursesIdEditRouteImport } from './routes/ceo.courses.$id.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InchargeRoute = InchargeRouteImport.update({
  id: '/incharge',
  path: '/incharge',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoRoute = CeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const InchargeIndexRoute = InchargeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InchargeRoute,
} as any)
const CeoIndexRoute = CeoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CeoRoute,
} as any)
const MemberFocusRoute = MemberFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => MemberRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InchargeReviewsRoute = InchargeReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => InchargeRoute,
} as any)
const InchargeAttendanceRoute = InchargeAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => InchargeRoute,
} as any)
const CeoSeedRoute = CeoSeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => CeoRoute,
} as any)
const CeoFranchisesRoute = CeoFranchisesRouteImport.update({
  id: '/franchises',
  path: '/franchises',
  getParentRoute: () => CeoRoute,
} as any)
const CeoAttendanceRoute = CeoAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => CeoRoute,
} as any)
const CeoAssignRoute = CeoAssignRouteImport.update({
  id: '/assign',
  path: '/assign',
  getParentRoute: () => CeoRoute,
} as any)
const CeoCoursesIndexRoute = CeoCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => CeoRoute,
} as any)
const MemberCoursesIdRoute = MemberCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => MemberRoute,
} as any)
const CeoCoursesIdEditRoute = CeoCoursesIdEditRouteImport.update({
  id: '/courses/$id/edit',
  path: '/courses/$id/edit',
  getParentRoute: () => CeoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ceo': typeof CeoRouteWithChildren
  '/incharge': typeof InchargeRouteWithChildren
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ceo/assign': typeof CeoAssignRoute
  '/ceo/attendance': typeof CeoAttendanceRoute
  '/ceo/franchises': typeof CeoFranchisesRoute
  '/ceo/seed': typeof CeoSeedRoute
  '/incharge/attendance': typeof InchargeAttendanceRoute
  '/incharge/reviews': typeof InchargeReviewsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/member/focus': typeof MemberFocusRoute
  '/ceo/': typeof CeoIndexRoute
  '/incharge/': typeof InchargeIndexRoute
  '/member/': typeof MemberIndexRoute
  '/member/courses/$id': typeof MemberCoursesIdRoute
  '/ceo/courses/': typeof CeoCoursesIndexRoute
  '/ceo/courses/$id/edit': typeof CeoCoursesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ceo/assign': typeof CeoAssignRoute
  '/ceo/attendance': typeof CeoAttendanceRoute
  '/ceo/franchises': typeof CeoFranchisesRoute
  '/ceo/seed': typeof CeoSeedRoute
  '/incharge/attendance': typeof InchargeAttendanceRoute
  '/incharge/reviews': typeof InchargeReviewsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/member/focus': typeof MemberFocusRoute
  '/ceo': typeof CeoIndexRoute
  '/incharge': typeof InchargeIndexRoute
  '/member': typeof MemberIndexRoute
  '/member/courses/$id': typeof MemberCoursesIdRoute
  '/ceo/courses': typeof CeoCoursesIndexRoute
  '/ceo/courses/$id/edit': typeof CeoCoursesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ceo': typeof CeoRouteWithChildren
  '/incharge': typeof InchargeRouteWithChildren
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ceo/assign': typeof CeoAssignRoute
  '/ceo/attendance': typeof CeoAttendanceRoute
  '/ceo/franchises': typeof CeoFranchisesRoute
  '/ceo/seed': typeof CeoSeedRoute
  '/incharge/attendance': typeof InchargeAttendanceRoute
  '/incharge/reviews': typeof InchargeReviewsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/member/focus': typeof MemberFocusRoute
  '/ceo/': typeof CeoIndexRoute
  '/incharge/': typeof InchargeIndexRoute
  '/member/': typeof MemberIndexRoute
  '/member/courses/$id': typeof MemberCoursesIdRoute
  '/ceo/courses/': typeof CeoCoursesIndexRoute
  '/ceo/courses/$id/edit': typeof CeoCoursesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ceo'
    | '/incharge'
    | '/login'
    | '/member'
    | '/profile'
    | '/reset-password'
    | '/ceo/assign'
    | '/ceo/attendance'
    | '/ceo/franchises'
    | '/ceo/seed'
    | '/incharge/attendance'
    | '/incharge/reviews'
    | '/invite/$token'
    | '/member/focus'
    | '/ceo/'
    | '/incharge/'
    | '/member/'
    | '/member/courses/$id'
    | '/ceo/courses/'
    | '/ceo/courses/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/ceo/assign'
    | '/ceo/attendance'
    | '/ceo/franchises'
    | '/ceo/seed'
    | '/incharge/attendance'
    | '/incharge/reviews'
    | '/invite/$token'
    | '/member/focus'
    | '/ceo'
    | '/incharge'
    | '/member'
    | '/member/courses/$id'
    | '/ceo/courses'
    | '/ceo/courses/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/ceo'
    | '/incharge'
    | '/login'
    | '/member'
    | '/profile'
    | '/reset-password'
    | '/ceo/assign'
    | '/ceo/attendance'
    | '/ceo/franchises'
    | '/ceo/seed'
    | '/incharge/attendance'
    | '/incharge/reviews'
    | '/invite/$token'
    | '/member/focus'
    | '/ceo/'
    | '/incharge/'
    | '/member/'
    | '/member/courses/$id'
    | '/ceo/courses/'
    | '/ceo/courses/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CeoRoute: typeof CeoRouteWithChildren
  InchargeRoute: typeof InchargeRouteWithChildren
  LoginRoute: typeof LoginRoute
  MemberRoute: typeof MemberRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incharge': {
      id: '/incharge'
      path: '/incharge'
      fullPath: '/incharge'
      preLoaderRoute: typeof InchargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo': {
      id: '/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof CeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/incharge/': {
      id: '/incharge/'
      path: '/'
      fullPath: '/incharge/'
      preLoaderRoute: typeof InchargeIndexRouteImport
      parentRoute: typeof InchargeRoute
    }
    '/ceo/': {
      id: '/ceo/'
      path: '/'
      fullPath: '/ceo/'
      preLoaderRoute: typeof CeoIndexRouteImport
      parentRoute: typeof CeoRoute
    }
    '/member/focus': {
      id: '/member/focus'
      path: '/focus'
      fullPath: '/member/focus'
      preLoaderRoute: typeof MemberFocusRouteImport
      parentRoute: typeof MemberRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incharge/reviews': {
      id: '/incharge/reviews'
      path: '/reviews'
      fullPath: '/incharge/reviews'
      preLoaderRoute: typeof InchargeReviewsRouteImport
      parentRoute: typeof InchargeRoute
    }
    '/incharge/attendance': {
      id: '/incharge/attendance'
      path: '/attendance'
      fullPath: '/incharge/attendance'
      preLoaderRoute: typeof InchargeAttendanceRouteImport
      parentRoute: typeof InchargeRoute
    }
    '/ceo/seed': {
      id: '/ceo/seed'
      path: '/seed'
      fullPath: '/ceo/seed'
      preLoaderRoute: typeof CeoSeedRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/franchises': {
      id: '/ceo/franchises'
      path: '/franchises'
      fullPath: '/ceo/franchises'
      preLoaderRoute: typeof CeoFranchisesRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/attendance': {
      id: '/ceo/attendance'
      path: '/attendance'
      fullPath: '/ceo/attendance'
      preLoaderRoute: typeof CeoAttendanceRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/assign': {
      id: '/ceo/assign'
      path: '/assign'
      fullPath: '/ceo/assign'
      preLoaderRoute: typeof CeoAssignRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/courses/': {
      id: '/ceo/courses/'
      path: '/courses'
      fullPath: '/ceo/courses/'
      preLoaderRoute: typeof CeoCoursesIndexRouteImport
      parentRoute: typeof CeoRoute
    }
    '/member/courses/$id': {
      id: '/member/courses/$id'
      path: '/courses/$id'
      fullPath: '/member/courses/$id'
      preLoaderRoute: typeof MemberCoursesIdRouteImport
      parentRoute: typeof MemberRoute
    }
    '/ceo/courses/$id/edit': {
      id: '/ceo/courses/$id/edit'
      path: '/courses/$id/edit'
      fullPath: '/ceo/courses/$id/edit'
      preLoaderRoute: typeof CeoCoursesIdEditRouteImport
      parentRoute: typeof CeoRoute
    }
  }
}

interface CeoRouteChildren {
  CeoAssignRoute: typeof CeoAssignRoute
  CeoAttendanceRoute: typeof CeoAttendanceRoute
  CeoFranchisesRoute: typeof CeoFranchisesRoute
  CeoSeedRoute: typeof CeoSeedRoute
  CeoIndexRoute: typeof CeoIndexRoute
  CeoCoursesIndexRoute: typeof CeoCoursesIndexRoute
  CeoCoursesIdEditRoute: typeof CeoCoursesIdEditRoute
}

const CeoRouteChildren: CeoRouteChildren = {
  CeoAssignRoute: CeoAssignRoute,
  CeoAttendanceRoute: CeoAttendanceRoute,
  CeoFranchisesRoute: CeoFranchisesRoute,
  CeoSeedRoute: CeoSeedRoute,
  CeoIndexRoute: CeoIndexRoute,
  CeoCoursesIndexRoute: CeoCoursesIndexRoute,
  CeoCoursesIdEditRoute: CeoCoursesIdEditRoute,
}

const CeoRouteWithChildren = CeoRoute._addFileChildren(CeoRouteChildren)

interface InchargeRouteChildren {
  InchargeAttendanceRoute: typeof InchargeAttendanceRoute
  InchargeReviewsRoute: typeof InchargeReviewsRoute
  InchargeIndexRoute: typeof InchargeIndexRoute
}

const InchargeRouteChildren: InchargeRouteChildren = {
  InchargeAttendanceRoute: InchargeAttendanceRoute,
  InchargeReviewsRoute: InchargeReviewsRoute,
  InchargeIndexRoute: InchargeIndexRoute,
}

const InchargeRouteWithChildren = InchargeRoute._addFileChildren(
  InchargeRouteChildren,
)

interface MemberRouteChildren {
  MemberFocusRoute: typeof MemberFocusRoute
  MemberIndexRoute: typeof MemberIndexRoute
  MemberCoursesIdRoute: typeof MemberCoursesIdRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberFocusRoute: MemberFocusRoute,
  MemberIndexRoute: MemberIndexRoute,
  MemberCoursesIdRoute: MemberCoursesIdRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CeoRoute: CeoRouteWithChildren,
  InchargeRoute: InchargeRouteWithChildren,
  LoginRoute: LoginRoute,
  MemberRoute: MemberRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
